### ISSUE TITLE
Add Functionality to Download from OData API

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/gss-utils#150]
This is the epic issue to track the MVP associated with downloading from an OData API and converting this data into CSV-W for handover to Swirl for PMD.

# Subtasks
- [x] #151 Download from API: Get Periods from OData API
- [x] #152 Download from API: Get Periods from SPARQL
- [x] #153 Download from API: Get Period Difference, Select Next
- [x] #154 Download from API: Get supplementary/linked datasets from OData
- [x] #155 Download from API: Get main dataset from OData
- [x] #156 Download from API: Join main and supplementary/linked datasets

# Example Data Pipeline
The approach will satisfy the following data pipeline steps.

The notation for each line is as follows:
```
* is MVP
! is stuff we will do, but not MVP
+ is manual stuff which will exist in dataset's main.py
```
## Step 1: initialise +
- cubes +
- scraper +

## Step 2: compare endpoints +
- get periods on odata as operiods *
- get periods on sparql as speriods * 
- translate operiods to speriods +
- pass speriods and operiods to compare !
  - save result as next_period +

## Step 3: get data +
- dataset.as_pandas(period=next_period) *
- sup_dfs.fetch() *

## Step 4 complete dataset +
- merge() !

## Step 5 finish +
- output everything after adding to cubes +

**Comment by canwaf** [comment]
There are some failing tests which need fixing.

1) Merge master back in
2) See if that fixes the failing tests
3) If not investigate the following tests:
```
Failing scenarios:
  features/csv2rdf.feature:144  Create CSVW metadata for CSV2RDF with dataset metadata
  features/csvw.feature:54  Data Cube, metadata and reference data for PMD4
  features/distribution.feature:19  pandas with nrscotland XLSX
  features/distribution.feature:45  Home Office ODS tab as Pandas DataFrame
  features/distribution.feature:50  Home Office ODS tabs as dict of Pandas DataFrames
  features/distribution.feature:55  DfT statistics data set
  features/distribution.feature:78  StatsWales OData API
  features/distribution.feature:90  NHS Digital Open data CSV
```

**Comment by canwaf** [comment]
First two tests fixed by skipping the skipped tests, the latter six solved by amending `dcat.py` to check first if there's a seed then check if it's an odata dataset.
