### ISSUE TITLE
Feature: Geo/Time coverage/resolution metadata

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/gss-utils#172]
Supports: End users finding data

Some datasets include spatio-temporal coverage and resolution as metadata in the spreadsheet or methodology, while others will include this in the title of the dataset, e.g. "LSOA Electricity Consumption". Often this information is implicit in the context of the dataset.

As BAs collect the landscape and details of a dataset and then DMs manage the metadata and reference data details, we need to make the spatio-temporal coverage and resolution explicit such that it can be represented as dataset metadata using DCAT and extensions.

These properties could be added to Airtable, though the main place to record them should be the `info.json` file associated with the dataset.

- [ ] Ensure gss-utils metadata/scraper can pick up coverage/resolution and add it to the dataset metadata. GSS-Cogs/gss-utils#78
- [ ] Add a task to each dataset/transform issue to remind us to record this info. GSS-Cogs/airtable-utils#9

**Comment by ajtucker** [comment]
See also https://github.com/Swirrl/cogs-issues/issues/92

**Comment by ajtucker** [comment]
- [ ] Implement custom spatio/temporal metadata properties in gss-utils as per https://github.com/Swirrl/cogs-issues/issues/92
- [ ] Pick an example dataset and add values to those properties in the transform itself.

**Comment by rossbowen** [comment]
https://github.com/GSS-Cogs/gss-utils/blob/a85ce1428cad003c5f9e05d0ecf821275ef4ddb3/gssutils/metadata/pmdcat.py#L43-L55

Additional properties can go here, and can be set as attributes against the scraper (`scraper.dataset.whatever`). We can provide some helper methods.

https://github.com/GSS-Cogs/gss-utils/blob/a85ce1428cad003c5f9e05d0ecf821275ef4ddb3/gssutils/scrape.py#L362-L363

https://github.com/GSS-Cogs/gss-utils/blob/a85ce1428cad003c5f9e05d0ecf821275ef4ddb3/gssutils/scrape.py#L401-L403

**Comment by Robsteranium** [comment]
Is the proposal to add these as hard-coded fields in the `info.json`? Ultimately we ought to be able to derive these from the observation data which would mean they didn't need to be maintained by hand. I've provided some [example queries](https://github.com/Swirrl/cogs-issues/issues/92#issuecomment-861559688) which demonstrate how this might work.

**Comment by canwaf** [comment]
I agree with @Robsteranium that resolution and (spatial/temporal) bounds should come from the data itself. Are you happy with this @rossbowen ?
