### ISSUE TITLE
Epic: family metadata, multiple families, themes, multiple taxonomies

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#174]
To date we've used "family" as the way to group datasets related by their shared dimensions. We have used the `gdp:family` property to record which family or families a dataset belongs to.

A dataset family is either explicitly recorded in the dataset transform script, e.g. `scraper.dataset.family = 'Trade'` (maybe taken from the spreadsheet), or it is picked up from the first entry in the `families` list in the`info.json` file.

We've recently started using `dcat:theme` to record the same thing, but here there are questions about what theme URI to use and how to allow multiple families and themes and which taxonomies to use.

Also, since a dataset can be in more than one family, we need to be careful that we don't end up duplicating work if we come across the same dataset again. We use the dataset's family as part of the path in the URI of a dataset, so if there are more than one family, we might want to pick a primary family and where a dataset shows up elsewhere, link it back to its primary family.

Things to do:

- [ ] Allow more than one family/theme and test that the output is right.
- [ ] Find what themes/taxonomies are being used and coin URIs, concept schemes, vocabs for them.
- [ ] Distinguish between "family" (and superfamily) as we're using it and the "theme" that the publisher uses to publish their data.

**Comment by rossbowen** [comment]
@ajtucker what are your thoughts on dropping the family name from the URI of a dataset?

**Comment by ajtucker** [comment]
> @ajtucker what are your thoughts on dropping the family name from the URI of a dataset?

I think that the `dcat:Dataset`'s URI should actually be the landing page `+ '#dataset'` and that the CSV-W (CSV + JSON) should be `dcat:Distribution`s that ideally are published alongside all the other distributions around the landing page, or in our case end up either published in Jenkins as part of the job, or more likely published on PMD, so need to be given a resolvable HTTP URI along the lines of `http://gss-data.org.uk/.../family/.../blah.csv(-metadata.json)?` that returns the tidy CSV/JSON.

Since the resulting `qb:DataSet` can be thought of as just another representation of the CSV-W distribution, we could use the same URI, though more probably we'd do some fiddling with fragment IDs or suffixes.

**Comment by rossbowen** [comment]
Made a start with https://github.com/GSS-Cogs/GDP-vocabs/issues/6. (https://github.com/GSS-Cogs/GDP-vocabs/commit/893427ca2cbe15c869e777e524cee09df69abed8) No ONS taxonomy atm.

**Comment by ajtucker** [comment]
Stats authority themes are no longer being generated, see GSS-Cogs/ref_common#10.

**Comment by canwaf** [comment]
csvcubed supports multiple keywords, @ajtucker. Is this enough?
